lang_name: "Українська"

title: "Лігво Друїда"
description: "Вітаємо! Приєднуйтесь до нашої спільноти, щоб бути в курсі останніх доповнень, аддонів і всього, що покращить ваш ігровий досвід!"

donate: "Пожертвувати"
legal: "Умови"
community: "Спільнота"
contribute: "Співпрацювати"

news: "Новини"
view_all: "Переглянути все"
read_more: "Продовжити читання"

community_desc: "Спосіб зв'язку для вирішення різних проблем, а також підтримки користувачів."
contribute_craftrom_github: "Підтримка різноманітних пристроїв на основі власної операційної системи Android."
support_craftrom: "Підтримка CraftRom"
telegram_group: "Група Telegram"
telegram_group_text: "Для обговорення пристроїв, функцій або просто загального спілкування про Android, перегляньте наш телеграм."
telegram_news_channel: "Новини в Telegram"
telegram_news_channel_text: "Оновлення ROM-ів, ядер та інші новини."

footer_note: "Примітка: CraftRom LLC не є неприбутковою організацією 501(c)(3), тому пожертви не є звільненими від оподаткування."
footer_page_last_update: "Останнє оновлення сторінки:"
footer_site_last_update: "Останнє оновлення сайту:"

donate_desc: "Тут ви маєте можливість сприяти розвитку проєкту фінансово."
donate_attention: "Увага!"
donate_attention_desc: "Натисканням будь-якої кнопки нижче та завершенням транзакції ви підтверджуєте, що є законним власником коштів."

404_title: "404 - Сторінку не знайдено"
404_desc: "Вибачте, ми не можемо знайти ту сторінку, яку ви шукаєте."
404_btn: "На головну сторінку"
